branch: main
directory:
  - ./checkov-files
download-external-modules: true
skip-check:
  - CKV_AWS_21
  - CKV_AWS_19
  - CKV_AWS_145
  - CKV2_AWS_6
  - CKV_AWS_144
  - CKV_AWS_18
skip-framework:
  - kubernetes
  - terraform
soft-fail: false